import { ERC20, WPOL } from './erc20'

export const NATIVE = {
  CHAIN: 137,
  DECIMALS: 18,
  SYMBOL: 'POL',
  NAME: 'Matic Token',

  WRAPPED: {
    ADDRESS: ERC20.ADDRESS[WPOL],
    DECIMALS: ERC20.DECIMALS[WPOL],
    SYMBOL: ERC20.SYMBOL[WPOL],
    DESCRIPTION: ERC20.DESCRIPTION[WPOL],
  }
}

